name: Upload Python Package to PyPI (Trusted Publishing)

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    environment: pypi 
    
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Build Source and Wheel distributions
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 
